networks:
  application_network:
    driver: bridge

volumes:
  mongodb: {}

services:
  api:
    build: .
    networks:
      - application_network
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    networks:
      - application_network
    volumes:
      - mongodb:/data/db